ALTER TABLE "users" ADD COLUMN "refreshToken" TEXT;

ALTER TYPE "OrderStatus" RENAME VALUE 'PENDING_REVIEW' TO 'PENDING';
ALTER TYPE "OrderStatus" RENAME VALUE 'AWAITING_PAYMENT' TO 'PAID';

ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'PENDING';
